# Generated by Django 5.0.2 on 2024-02-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='PreparationDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preparation')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='preparations',
            field=models.ManyToManyField(through='core.PreparationDirective', to='core.preparation'),
        ),
    ]
